Gem::Specification.new do |s|
  s.name        = 'my_grocery_deals'
  s.version     = '2.4.0'
  s.summary     = 'my_grocery_deals'
  s.description = 'This API SDK was automatically generated by APIMATIC Beta 2.0'
  s.authors     = ["APIMATIC", "Zeeshan Ejaz Bhatti", "Dennis O'Connor"]
  s.email       = 'doconnor@mygrocerydeals.com'
  s.homepage    = 'https://mygrocerydeals.com'
  s.license     = 'MIT'

  s.add_dependency('unirest', '~> 1.1.2')
  s.required_ruby_version = '~> 2.0'

  s.files       = Dir['{bin,lib,man,test,spec}/**/*', 'README*', 'LICENSE*']
  s.require_paths = ['lib']

end
