# This file was automatically generated by APIMATIC BETA v2.0 on 10/09/2015

module MyGroceryDeals
  class Configuration

    # The base Uri for API calls
    BASE_URI = ENV["MGD_BASE_URI"] || "https://api.mygrocerydeals.com/v%s"

    VERSION = "2"

    # API key as a custom request header. Do not use together with "api_key" request parameter
    X_API_KEY = ENV['MGD_API_KEY']
  end
end
