# This file was automatically generated by APIMATIC BETA v2.0 on 10/09/2015
require 'openssl'
require 'json'
require 'unirest'

# APIMATIC Helper Files
require 'my_grocery_deals/api_helper.rb'
require 'my_grocery_deals/api_exception.rb'
require 'my_grocery_deals/configuration.rb'

# Controllers
require 'my_grocery_deals/controllers/deals_controller.rb'
require 'my_grocery_deals/controllers/deal_controller.rb'
require 'my_grocery_deals/controllers/stores_controller.rb'
require 'my_grocery_deals/controllers/store_controller.rb'
require 'my_grocery_deals/controllers/categories_controller.rb'
require 'my_grocery_deals/controllers/category_controller.rb'
require 'my_grocery_deals/controllers/chains_controller.rb'
require 'my_grocery_deals/controllers/chain_controller.rb'
require 'my_grocery_deals/controllers/geo_controller.rb'

# Models
